name: Lint and test

on:
  push:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Lint and test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [16, 18]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}

    services:
      mongo:
        image: "mongo:6.0"
        ports:
          # Maps port 27017 on service container to the host
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
        with:
          repository: NodeBB/NodeBB

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: yarn Install
        run: yarn

      # set up the tested plugin
      - uses: actions/checkout@v3
        with:
          path: tested_plugin
      - name: Install the tested plugin
        run: yarn add file:./tested_plugin

      - name: Setup on MongoDB
        env:
          SETUP: >-
            {
              "url": "http://127.0.0.1:4567",
              "secret": "abcdef",
              "admin:username": "admin",
              "admin:email": "test@example.org",
              "admin:password": "hAN3Eg8W",
              "admin:password:confirm": "hAN3Eg8W",

              "database": "mongo",
              "mongo:host": "127.0.0.1",
              "mongo:port": 27017,
              "mongo:username": "",
              "mongo:password": "",
              "mongo:database": "nodebb",
              "test_plugins": ["${{ github.event.repository.name }}"]
            }
          CI: >-
            {
              "host": "127.0.0.1",
              "port": 27017,
              "database": "ci_test"
            }
        run: |
          node app --setup="${SETUP}" --ci="${CI}"
      - name: Run ESLint
        run: yarn lint

      - name: Node tests
        run: yarn test test/plugins-installed.js

      - name: Extract coverage info
        run: yarn coverage
